### ISSUE TITLE
(request for feature) Option to prefetch data into disk (instead of memory)

### ISSUE THREAD

**Issue by dur3x** [warren-bank/HLS-Proxy#30]
First of all, thanks a lot for all your great job, it's awesome and I use it everyday ;-)

This issue is just a request for feature about the prefetch option.
The prefetch option works fine by using the memory but I have some case in which I'm limited with the memory but want to benefit from the prefetch option.
So I think it would be great to have an option to be able to prefetch on disk

**Comment by warren-bank** [comment]
you got it..

[v3.4.0](https://github.com/warren-bank/HLS-Proxy/releases/tag/v3.4.0) adds the ability to write the cache of video segments to the filesystem, rather than holding it in RAM.

* reads and writes will be a bit slower.. though I didn't notice any real-world difference in video playback when I tested it
* if using a HDD, there will be some added wear-and-tear.. since there are moving parts
* otherwise, idk.. give it a shot and let me know how it works :smiley:

for example:
```bash
hlsd --port 8080 -v 1 --prefetch --cache-storage "filesystem" --cache-storage-fs-dirpath "/path/to/cache/directory"
```

**Comment by dur3x** [comment]
Thank you so much :-) I can confirm, it works perfectly 🥇
