### ISSUE TITLE
Access controls

### ISSUE THREAD

**Issue by Daniel15** [warren-bank/HLS-Proxy#7]
Thanks for this project! I'm trying it out as a proxy for geogated TV streams (so that I can watch free TV channels from my home country while living abroad) and it's working quite well for that use case.

I was wondering if there's currently any option for access controls, such as being able to use Basic authentication (username + password) or restrict connections so they can only come from particular IP addresses. I'd like to restrict my instance so that only I can connect to it.

I'm happy to look through the code and send a pull request if this is not currently available, just wanted to check first :)

Also, can you confirm that the proxy doesn't use any bandwidth if it's not actively being used (assuming prefetching is disabled)? I'd like to leave it running 24/7 but don't want it to keep consuming streams after I disconnect my client.

Thanks!

**Comment by warren-bank** [comment]
I'm glad you find the app useful.

There isn't currently any way to restrict access, but I'm also not opposed to the idea. I probably wouldn't use special http request headers, since many video clients couldn't be configured to send them (ex: chromecast). A simple IP whitelist would be lightweight and effective (ex: `--acl-whitelist "192.168.1.100,192.168.1.101,192.168.1.102"`). Would that work?

As for bandwidth, you're correct; the proxy sits completely idle waiting for a connection when not in use. When a connection is received, the request includes a url which the proxy downloads from the network (with modified request headers, etc) and pipes the response back to the client. Once the response is complete, the connection is closed. The proxy again returns to a completely idle state.

**Comment by warren-bank** [comment]
I went ahead and added the `--acl-whitelist` option to `v0.14.0`, which was just pushed to _npm_.

Hope that meets your need.

**Comment by Daniel15** [comment]
Thank you! I think that will be sufficient. I'll try it some time this week.

Does it work with IPv6? Some of my servers are IPv6-only.

**Comment by warren-bank** [comment]
Tentative "yes". Though I only tested it with IPv4, [node.js appears to convert](https://stackoverflow.com/questions/31100703/stripping-ffff-prefix-from-request-connection-remoteaddress-nodejs) all [IPv4 IP addresses to IPv6](https://en.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses).. which is why I needed to [apply a regex filter](https://github.com/warren-bank/HLS-Proxy/blob/v0.14.0/hls-proxy/proxy.js#L202) to remove the unwanted static prefix. That being said, I would assume that IPv6 should work just fine.. assuming that your valid IPv6 doesn't contain this static prefix `::ffff:` that gets removed.

**Comment by Daniel15** [comment]
Thanks! I think this should work for me. My ISP uses dynamic IP addressing but I think I can create a script to periodically get the current IP from a dynamic DNS service and update the ACL / restart the proxy if it changes.
